### ISSUE TITLE
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

### ISSUE THREAD

**Issue by Xuekai-Zhu** [matt-seb-ho/gfn_ntp#3]
Hi! There is an error happening of the latest version. Maybe there is something wrong with lean_dojo ?
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/lean_dojo/interaction/dojo.py", line 418, in _read_next_line
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pexpect/spawnbase.py", line 354, in expect
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pexpect/spawnbase.py", line 383, in expect_list
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pexpect/expect.py", line 179, in expect_loop
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pexpect/expect.py", line 122, in eof
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x155480aaa500>
command: /home/zhuxuekai/.elan/bin/lake
args: [b'/home/zhuxuekai/.elan/bin/lake', b'env', b'lean', b'--threads=1', b'--memory=32768', b'Mathlib/Data/Int/Cast/Basicmfmrb3u_.lean']
buffer (last 100 chars): ''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 1773024
child_fd: 173
closed: False
timeout: 60
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 1
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('\n')
    1: re.compile('REPL>.*?\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/lean_dojo/interaction/dojo.py", line 188, in __enter__
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/lean_dojo/interaction/dojo.py", line 429, in _read_next_line
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/gfn_tuning/ntp.py", line 468, in training_step
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/gfn_tuning/ntp.py", line 201, in parallel_forward
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/lean_env_cache.py", line 45, in get
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/lean_dojo/interaction/dojo.py", line 195, in __enter__
lean_dojo.interaction.dojo.DojoInitError: Unexpected EOF
```

**Comment by matt-seb-ho** [comment]
Hi, thanks for reaching out! This is error is one we have seen during development and from my notes it looks like it was a dependency issue. I recommend checking that your lean dojo version matches the one used to trace mathlib. LeanDojo maintainers periodically update the cached version of the traced mathlib repo and LeanDojo automatically pulls from this remote cache if it recognizes the repo id/hash.

**Comment by Xuekai-Zhu** [comment]
Thanks for your quick reply! 
BTW, i have another problem for version of LeanDojo:
v 2.1.3 will trigger the following bug, however the v 2.1.3 will not.
```
srun: job 7903997 queued and waiting for resources
srun: job 7903997 has been allocated resources
[2024-12-09 16:37:23,544] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Warning: The cache directory for DeepSpeed Triton autotune, /home/zhuxuekai/.triton/autotune, appears to be on an NFS system. While this is generally acceptable, if you experience slowdowns or hanging when DeepSpeed exits, it is recommended to set the TRITON_CACHE_DIR environment variable to a non-NFS path.
Traceback (most recent call last):
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/scripts/gfn_tuning/train.py", line 30, in <module>
    from proof_flow.src.gfn_tuning.ntp import NeuralTheoremProvingTask
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/gfn_tuning/ntp.py", line 33, in <module>
    from proof_flow.src.search.proof_search import (
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/search/proof_search.py", line 20, in <module>
    from proof_flow.src.search.search_tree import *
  File "/scratch2/nlp/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/search/search_tree.py", line 13, in <module>
    from lean_dojo import ( # isort: skip
ImportError: cannot import name 'TimeoutError' from 'lean_dojo' (/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/lean_dojo/__init__.py)
srun: error: hgx-hyperplane05: task 0: Exited with exit code 1
```

**Comment by Xuekai-Zhu** [comment]
sorry to bother you again. 
Can you privide me your code to figure out: 
how to check that your lean dojo version matches the one used to trace mathlib ?

**Comment by Xuekai-Zhu** [comment]
I finally solved this bug by:
remove all dependencies installed before.
Then:
```
1. install elan
2. install leandojo from main branch
3. the eof error disappear.
```
Thank you very much for your quick reply!

And i also find some others discussions, which may be helpful for others:

1. (Leandojo didn't trace newly created .lean file)[https://github.com/lean-dojo/LeanDojo/issues/91]
2. (lean_dojo.interaction.dojo.DojoCrashError: Unexpected EOF)[https://github.com/lean-dojo/LeanDojo/discussions/207]

**Comment by matt-seb-ho** [comment]
Thank you for including your detailed solution and helpful links! I believe I made a slight mistake in my initial response. My early setup notes are admittedly incomplete, so I’m unsure if there’s an easy way to check remote cache versioning. However, I do remember encountering dependency issues where the solution was often to update all components (benchmark dataset, Lean Dojo, Lean runtime) to the latest versions and clear the cache as a precaution.

Apologies for the delayed response. As I mentioned in [issue #4](https://github.com/matt-seb-ho/gfn_ntp/issues/4), I’m currently attending NeurIPS 2024, which has been taking up much of my attention. I’ll be available to assist more next week.

Thank you for your understanding!

**Comment by matt-seb-ho** [comment]
>v 2.1.3 will trigger the following bug, however the v 2.1.2 will not.

To clarify, this behaviour makes sense as the work was completed under v2.1.2. The fix should be to remove `TimeoutError` from the repository as it is no longer used in these later versions. I will complete this fix as soon as I can.

**Comment by Xuekai-Zhu** [comment]
Thank you very much for your response and explanation! This is truly an amazing project，which is very helpfule for me! 
I hope you have a great time at NeurIPS as well!

BTW, I have checked that lean-dojo 2.2.0 (latest) works well for `remove TimeoutError`.
