### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by Xuekai-Zhu** [matt-seb-ho/gfn_ntp#4]
When training at Epoch 0:  46%, I met the following error in `for key in self.cache.keys():`. 

```
3820   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
3821     self.epoch_loop.run(self._data_fetcher)
3822   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
3823     self.advance(data_fetcher)
3824   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 250, in advance
3825     batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
3826   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 190, in run
3827     self._optimizer_step(batch_idx, closure)
3828   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 268, in _optimizer_step
3829     call._call_lightning_module_hook(
3830   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 167, in _call_lightning_module_hook
3831     output = fn(*args, **kwargs)
3832   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1306, in optimizer_step
3833     optimizer.step(closure=optimizer_closure)
3834   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 153, in step
3835     step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
3836   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 238, in optimizer_step
3837     return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
3838   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision.py", line 122, in optimizer_step
3839     return optimizer.step(closure=closure, **kwargs)
3840   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/optim/optimizer.py", line 487, in wrapper
3841     out = func(*args, **kwargs)
3842   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/optim/optimizer.py", line 91, in _use_grad
3843     ret = func(self, *args, **kwargs)
3844   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/optim/adamw.py", line 197, in step
3845     loss = closure()
3846   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision.py", line 108, in _wrap_closure
3847     closure_result = closure()
3848   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 144, in __call__
3849     self._result = self.closure(*args, **kwargs)
3850   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
3851     return func(*args, **kwargs)
3852   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 129, in closure
3853     step_output = self._step_fn()
3854   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 317, in _training_step
3855     training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
3856   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 319, in _call_strategy_hook
3857     output = fn(*args, **kwargs)
3858   File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in training_step
3859     return self.lightning_module.training_step(*args, **kwargs)
3860   File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/gfn_tuning/ntp.py", line 465, in training_step
3861     t_logpf, log_r, trajectories = self.parallel_forward(
3862   File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/gfn_tuning/ntp.py", line 201, in parallel_forward
3863     dojo, initial_state = self.dojo_cache.get(theorem)
3864   File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/lean_env_cache.py", line 50, in get
3865     self.clear()
3866   File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/lean_env_cache.py", line 61, in clear
3867     for key in self.cache.keys():
3868 RuntimeError: dictionary changed size during iteration
3869 
3870 Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by Xuekai-Zhu** [comment]
I have tried solution of  [4a100b8](https://github.com/matt-seb-ho/gfn_ntp/commit/4a100b8372900337d3b12807b29ae95a81fde529).

There is still raising error as follows:

```
Traceback (most recent call last):                                                                                                                 
  File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/scripts/gfn_tuning/train.py", line 46, in train                                
    trainer.fit(model=task, datamodule=data)                                                                                                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit             
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_int
errupt                                                                                                                                             
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run            
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1025, in _run_stage     
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run              
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance          
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run   
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 250, in advanc
e  
File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 190, in run
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 268, in _op
timizer_step                                                                                                                                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 167, in _call_lightning_mod
ule_hook                                                                                                                                           
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1306, in optimizer_step     
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 153, in step             
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 238, in optimizer_st
ep                                                                                                                                                 
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision.py", line 122, in opti
mizer_step                                                                                                                                         
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/optim/optimizer.py", line 487, in wrapper                     
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/optim/optimizer.py", line 91, in _use_grad                    
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/optim/adamw.py", line 197, in step                            
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision.py", line 108, in _wra
p_closure                                                                                                                                          
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 144, in __c
all__                                                                                                                                              
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context          
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 129, in clo
sure                                                                                                                                               
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 317, in _tr
aining_step                                                                                                                                        
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 319, in _call_strategy_hook
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in training_ste
p                                                                                                                                                  
  File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/gfn_tuning/ntp.py", line 465, in training_step                             
  File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/gfn_tuning/ntp.py", line 201, in parallel_forward                          
  File "/home/zhuxuekai/reasoning_flow/baselines/gfn_ntp/proof_flow/src/lean_env_cache.py", line 36, in get                                        
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/lean_dojo/interaction/dojo.py", line 176, in __enter__              
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pexpect/pty_spawn.py", line 205, in __init__                        
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pexpect/pty_spawn.py", line 303, in _spawn                          
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/pexpect/pty_spawn.py", line 315, in _spawnpty                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/ptyprocess/ptyprocess.py", line 230, in spawn                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/pty.py", line 101, in fork                                                        
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/pty.py", line 34, in openpty                                                      
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/pty.py", line 64, in _open_terminal                                               
OSError: out of pty devices 
Exception ignored in atexit callback: <bound method TemporaryDirectory.cleanup of <TemporaryDirectory '/tmp/tmp9038h7q3wandb-media'>>      [0/1767]
Traceback (most recent call last):                                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/tempfile.py", line 882, in cleanup                                                
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/tempfile.py", line 864, in _rmtree                                                
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/shutil.py", line 721, in rmtree                                                   
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/shutil.py", line 718, in rmtree                                                   
OSError: [Errno 24] Too many open files: '/tmp/tmp9038h7q3wandb-media'                                                                             
Exception ignored in atexit callback: <bound method TemporaryDirectory.cleanup of <TemporaryDirectory '/tmp/tmp8fv4tdizwandb-artifacts'>>          
Traceback (most recent call last):                                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/tempfile.py", line 882, in cleanup                                                
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/tempfile.py", line 864, in _rmtree                                                
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/shutil.py", line 721, in rmtree                                                   
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/shutil.py", line 718, in rmtree                                                   
OSError: [Errno 24] Too many open files: '/tmp/tmp8fv4tdizwandb-artifacts'                                                                         
Exception ignored in atexit callback: <function matmul_ext_update_autotune_table at 0x7fd4d9e8c0d0>                                                
Traceback (most recent call last):                                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 477,
 in matmul_ext_update_autotune_table
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 454,
 in _update_autotune_table          
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 177,
 in _update_autotune_table          
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 87, 
in __init__                         
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 44, 
in warn_if_nfs                      
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/deepspeed/ops/transformer/inference/triton/matmul_ext.py", line 27, 
in is_nfs_path                      
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/subprocess.py", line 421, in check_output                                         
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/subprocess.py", line 503, in run                                                  
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/subprocess.py", line 837, in __init__                                             
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/subprocess.py", line 1629, in _get_handles                                        
OSError: [Errno 24] Too many open files                                  
Exception ignored in atexit callback: <function shutdown at 0x7fd4dbfe3f40>                                                                        
Traceback (most recent call last):                                       
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper             
  File "/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/ray/_private/worker.py", line 1883, in shutdown                     
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load                                                                               
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked                                                                      
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked                                                                                
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module                                                                          
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code                                                                            
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data                                                                            
OSError: [Errno 24] Too many open files: '/home/zhuxuekai/miniconda3/envs/reasoning/lib/python3.10/site-packages/ray/dag/__init__.py'
```

**Comment by matt-seb-ho** [comment]
This is related to how LeanDojo objects work. Each Dojo object can handle one theorem at a time and wraps a lean repl and keeps a file open. Our filtering code includes a step to filter away theorems whose Dojo initialization require over 5 seconds. We further use the dojo cache to remove this startup time by keeping them open and in memory.

The OS limits the number of files it can have open at a time which should explain this issue. You can modify this limit with `ulimit`-- see [this StackOverflow answer](https://stackoverflow.com/questions/39537731/errno-24-too-many-open-files-but-i-am-not-opening-files).

**Comment by Xuekai-Zhu** [comment]
Thank you for detailed explanation.
I use the `ulimit -n` -> `131072`;
The  `131072` may be able to handle most tasks. However, i still met the bug `OSError: [Errno 24] Too many open files`.

is there any other bugs leading to `OSError: [Errno 24] Too many open files` ?

**Comment by matt-seb-ho** [comment]
I'm not aware of any other bugs that lead to that error. I can try to add additional error handling for that error. This would probably involve calling the cache cleanup function...
